# Generated by Django 5.1.1 on 2026-10-06 19:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'first_name',
                    models.CharField(max_length=50, verbose_name='Имя'),
                ),
                (
                    'last_name',
                    models.CharField(max_length=50, verbose_name='Фамилия'),
                ),
                (
                    'role',
                    models.CharField(
                        choices=[
                            ('HEAD_COACH', 'Главный тренер'),
                            ('ASSISTANT', 'Ассистент'),
                            ('DOCTOR', 'Врач'),
                            ('ADMIN', 'Администратор'),
                            ('OTHER', 'Другое'),
                        ],
                        max_length=20,
                        verbose_name='Должность',
                    ),
                ),
                (
                    'photo',
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to='staff/',
                        verbose_name='Фото',
                    ),
                ),
                (
                    'bio',
                    models.TextField(blank=True, verbose_name='О человеке'),
                ),
                (
                    'phone',
                    models.CharField(
                        blank=True, max_length=20, verbose_name='Телефон'
                    ),
                ),
                (
                    'email',
                    models.EmailField(
                        blank=True, max_length=254, verbose_name='Email'
                    ),
                ),
                (
                    'order',
                    models.PositiveSmallIntegerField(
                        default=100, verbose_name='Порядок отображения'
                    ),
                ),
                (
                    'is_active',
                    models.BooleanField(default=True, verbose_name='Работает'),
                ),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                (
                    'user',
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='staff_profile',
                        to=settings.AUTH_USER_MODEL,
                        verbose_name='Аккаунт',
                    ),
                ),
            ],
            options={
                'verbose_name': 'Сотрудник',
                'verbose_name_plural': 'Тренерский состав',
                'ordering': ['order', 'last_name', 'first_name'],
            },
        ),
    ]
