# Generated by Django 5.1.1 on 2026-10-05 18:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsPost',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'title',
                    models.CharField(max_length=200, verbose_name='Заголовок'),
                ),
                (
                    'slug',
                    models.SlugField(
                        blank=True,
                        max_length=200,
                        unique=True,
                        verbose_name='Слаг',
                    ),
                ),
                (
                    'cover',
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to='news/',
                        verbose_name='Обложка',
                    ),
                ),
                (
                    'excerpt',
                    models.CharField(
                        blank=True,
                        max_length=300,
                        verbose_name='Краткое описание',
                    ),
                ),
                ('content', models.TextField(verbose_name='Текст')),
                (
                    'is_published',
                    models.BooleanField(
                        default=True, verbose_name='Опубликовано'
                    ),
                ),
                (
                    'published_at',
                    models.DateTimeField(
                        auto_now_add=True, verbose_name='Дата публикации'
                    ),
                ),
                ('updated_at', models.DateTimeField(auto_now=True)),
                (
                    'author',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='news_posts',
                        to=settings.AUTH_USER_MODEL,
                        verbose_name='Автор',
                    ),
                ),
            ],
            options={
                'verbose_name': 'Новость',
                'verbose_name_plural': 'Новости',
                'ordering': ['-published_at'],
            },
        ),
    ]
