# Generated by Django 5.1.1 on 2026-10-06 19:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Training',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'title',
                    models.CharField(max_length=100, verbose_name='Название'),
                ),
                ('date', models.DateTimeField(verbose_name='Дата и время')),
                (
                    'duration_minutes',
                    models.PositiveSmallIntegerField(
                        default=90, verbose_name='Длительность (мин)'
                    ),
                ),
                (
                    'location',
                    models.CharField(max_length=200, verbose_name='Место'),
                ),
                (
                    'is_cancelled',
                    models.BooleanField(
                        default=False, verbose_name='Отменена'
                    ),
                ),
                (
                    'comment',
                    models.TextField(blank=True, verbose_name='Комментарий'),
                ),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                (
                    'coach',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='trainings',
                        to='staff.staff',
                        verbose_name='Тренер',
                    ),
                ),
            ],
            options={
                'verbose_name': 'Тренировка',
                'verbose_name_plural': 'Тренировки',
                'ordering': ['-date'],
            },
        ),
    ]
