# Generated by Django 5.1.1 on 2026-10-05 18:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'first_name',
                    models.CharField(max_length=50, verbose_name='Имя'),
                ),
                (
                    'last_name',
                    models.CharField(max_length=50, verbose_name='Фамилия'),
                ),
                (
                    'nickname',
                    models.CharField(
                        blank=True, max_length=50, verbose_name='Прозвище'
                    ),
                ),
                (
                    'number',
                    models.PositiveSmallIntegerField(
                        blank=True,
                        null=True,
                        unique=True,
                        verbose_name='Номер',
                    ),
                ),
                (
                    'position',
                    models.CharField(
                        choices=[
                            ('GK', 'Вратарь'),
                            ('DF', 'Защитник'),
                            ('WG', 'Крайний'),
                            ('FW', 'Нападающий'),
                        ],
                        max_length=2,
                        verbose_name='Позиция',
                    ),
                ),
                (
                    'birth_date',
                    models.DateField(
                        blank=True, null=True, verbose_name='Дата рождения'
                    ),
                ),
                (
                    'photo',
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to='players/',
                        verbose_name='Фото',
                    ),
                ),
                (
                    'bio',
                    models.TextField(blank=True, verbose_name='О команде'),
                ),
                (
                    'is_active',
                    models.BooleanField(
                        default=True, verbose_name='В команде'
                    ),
                ),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                (
                    'user',
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='player_profile',
                        to=settings.AUTH_USER_MODEL,
                        verbose_name='Аккаунт',
                    ),
                ),
            ],
            options={
                'verbose_name': 'Игрок',
                'verbose_name_plural': 'Игроки',
                'ordering': ['number'],
            },
        ),
    ]
