"""Числовые константы полей моделей."""

# --- User ---
USER_ROLE_MAX_LENGTH = 10
USER_PHONE_MAX_LENGTH = 20
USER_PASSWORD_MIN_LENGTH = 8

# --- Player ---
PLAYER_FIRST_NAME_MAX_LENGTH = 50
PLAYER_LAST_NAME_MAX_LENGTH = 50
PLAYER_NICKNAME_MAX_LENGTH = 50
PLAYER_POSITION_MAX_LENGTH = 2

# --- Match ---
MATCH_OPPONENT_MAX_LENGTH = 100
MATCH_LOCATION_MAX_LENGTH = 200
MATCH_STATUS_MAX_LENGTH = 3

# --- MatchEvent ---
MATCH_EVENT_TYPE_MAX_LENGTH = 10

# --- NewsPost ---
NEWS_TITLE_MAX_LENGTH = 200
NEWS_SLUG_MAX_LENGTH = 200
NEWS_EXCERPT_MAX_LENGTH = 300
COMMENT_TEXT_MAX_LENGTH = 1000

# --- API ---
API_PAGE_SIZE = 20

# --- JWT ---
JWT_ACCESS_MINUTES = 60
JWT_REFRESH_DAYS = 7

# --- Staff ---
STAFF_ROLE_MAX_LENGTH = 20
STAFF_PHONE_MAX_LENGTH = 20
STAFF_EMAIL_MAX_LENGTH = 254
STAFF_FIRST_NAME_MAX_LENGTH = 50
STAFF_LAST_NAME_MAX_LENGTH = 50

# --- Training ---
TRAINING_TITLE_MAX_LENGTH = 100
TRAINING_LOCATION_MAX_LENGTH = 200
TRAINING_DEFAULT_DURATION_MINUTES = 90

# --- Gallery ---
ALBUM_TITLE_MAX_LENGTH = 200
ALBUM_SLUG_MAX_LENGTH = 200
ALBUM_DESCRIPTION_MAX_LENGTH = 500
PHOTO_CAPTION_MAX_LENGTH = 300

# --- Site ---
SITE_NAME = 'ФК «Футзал»'
SITE_DESCRIPTION = (
    'Сайт мини-футбольной команды: расписание матчей, состав, '
    'статистика игроков, новости и фотогалерея.'
)
SITE_KEYWORDS = (
    'мини-футбол, футзал, команда, матчи, статистика, ' 'игроки, новости'
)

# --- Пагинация ---
PAGE_SIZE_NEWS = 10
PAGE_SIZE_MATCHES = 10
PAGE_SIZE_GALLERY = 12
PAGE_SIZE_TRAININGS = 10
