"""Числовые константы полей моделей."""

# --- User ---
USER_ROLE_MAX_LENGTH = 10
USER_PHONE_MAX_LENGTH = 20

# --- Player ---
PLAYER_FIRST_NAME_MAX_LENGTH = 50
PLAYER_LAST_NAME_MAX_LENGTH = 50
PLAYER_NICKNAME_MAX_LENGTH = 50
PLAYER_POSITION_MAX_LENGTH = 2

# --- Match ---
MATCH_OPPONENT_MAX_LENGTH = 100
MATCH_LOCATION_MAX_LENGTH = 200
MATCH_STATUS_MAX_LENGTH = 3

# --- MatchEvent ---
MATCH_EVENT_TYPE_MAX_LENGTH = 10

# --- NewsPost ---
NEWS_TITLE_MAX_LENGTH = 200
NEWS_SLUG_MAX_LENGTH = 200
NEWS_EXCERPT_MAX_LENGTH = 300

# --- API ---
API_PAGE_SIZE = 20

# --- JWT ---
JWT_ACCESS_MINUTES = 60
JWT_REFRESH_DAYS = 7
