# Generated by Django 5.1.1 on 2026-10-06 20:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('matches', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'title',
                    models.CharField(max_length=200, verbose_name='Название'),
                ),
                (
                    'slug',
                    models.SlugField(
                        blank=True,
                        max_length=200,
                        unique=True,
                        verbose_name='Слаг',
                    ),
                ),
                (
                    'description',
                    models.TextField(
                        blank=True, max_length=500, verbose_name='Описание'
                    ),
                ),
                (
                    'cover',
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to='gallery/covers/',
                        verbose_name='Обложка',
                    ),
                ),
                ('date', models.DateField(verbose_name='Дата события')),
                (
                    'is_published',
                    models.BooleanField(
                        default=True, verbose_name='Опубликован'
                    ),
                ),
                (
                    'order',
                    models.PositiveSmallIntegerField(
                        default=100, verbose_name='Порядок'
                    ),
                ),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                (
                    'match',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='albums',
                        to='matches.match',
                        verbose_name='Матч',
                    ),
                ),
            ],
            options={
                'verbose_name': 'Альбом',
                'verbose_name_plural': 'Фотоальбомы',
                'ordering': ['-date', 'order'],
            },
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'image',
                    models.ImageField(
                        upload_to='gallery/photos/', verbose_name='Фото'
                    ),
                ),
                (
                    'caption',
                    models.CharField(
                        blank=True, max_length=300, verbose_name='Подпись'
                    ),
                ),
                (
                    'order',
                    models.PositiveSmallIntegerField(
                        default=100, verbose_name='Порядок'
                    ),
                ),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                (
                    'album',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='photos',
                        to='gallery.album',
                        verbose_name='Альбом',
                    ),
                ),
            ],
            options={
                'verbose_name': 'Фотография',
                'verbose_name_plural': 'Фотографии',
                'ordering': ['order', 'id'],
            },
        ),
    ]
