# Generated by Django 5.1.1 on 2026-10-05 18:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('players', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'opponent',
                    models.CharField(max_length=100, verbose_name='Соперник'),
                ),
                (
                    'opponent_logo',
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to='opponents/',
                        verbose_name='Логотип соперника',
                    ),
                ),
                ('date', models.DateTimeField(verbose_name='Дата и время')),
                (
                    'location',
                    models.CharField(max_length=200, verbose_name='Место'),
                ),
                (
                    'is_home',
                    models.BooleanField(
                        default=True, verbose_name='Домашний матч'
                    ),
                ),
                (
                    'status',
                    models.CharField(
                        choices=[
                            ('SCH', 'Запланирован'),
                            ('FIN', 'Завершён'),
                            ('CAN', 'Отменён'),
                        ],
                        default='SCH',
                        max_length=3,
                        verbose_name='Статус',
                    ),
                ),
                (
                    'our_score',
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name='Наши голы'
                    ),
                ),
                (
                    'opponent_score',
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name='Голы соперника'
                    ),
                ),
                (
                    'comment',
                    models.TextField(blank=True, verbose_name='Комментарий'),
                ),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Матч',
                'verbose_name_plural': 'Матчи',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='MatchEvent',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'event_type',
                    models.CharField(
                        choices=[
                            ('GOAL', 'Гол'),
                            ('ASSIST', 'Передача'),
                            ('YELLOW', 'Жёлтая карточка'),
                            ('RED', 'Красная карточка'),
                            ('OWN', 'Автогол'),
                        ],
                        max_length=10,
                        verbose_name='Событие',
                    ),
                ),
                (
                    'minute',
                    models.PositiveSmallIntegerField(verbose_name='Минута'),
                ),
                (
                    'match',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='events',
                        to='matches.match',
                        verbose_name='Матч',
                    ),
                ),
                (
                    'player',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='events',
                        to='players.player',
                        verbose_name='Игрок',
                    ),
                ),
            ],
            options={
                'verbose_name': 'Событие матча',
                'verbose_name_plural': 'События матча',
                'ordering': ['minute'],
            },
        ),
    ]
